--Customer
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

--SELECT * FROM SURGE_PRICING;
--Customer Profile view

DROP VIEW VW_CUSTOMER_PROFILE;
DROP VIEW VW_CUSTOMER_TRIPS;
DROP VIEW VW_DRIVER_TRIPS;
DROP VIEW VW_SUPPORT_CASES;
DROP VIEW VW_REQUESTED_TRIPS;
DROP VIEW LOW_RATED_TRIPS;
DROP VIEW VW_DRIVER_WEEKLY_EARNINGS;
DROP VIEW VW_DRIVERS_WITHOUT_LICENSE;

CREATE OR REPLACE VIEW VW_CUSTOMER_PROFILE AS 
    SELECT FIRST_NAME, 
    LAST_NAME, 
    PHONE_NUMBER, 
    EMAIL, 
    ADDRESS_LINE_1, 
    ADDRESS_LINE_2, 
    ZIPCODE FROM CUSTOMER;

SELECT * FROM VW_CUSTOMER_PROFILE;

--  Trips for a particular customer
