GRANT EXECUTE ON PKG_TRIP_CANCELLATION TO APP_CUSTOMER, UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_COMPLETION TO UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_IN_PROGRESS TO UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_REQUEST TO APP_CUSTOMER, FLEET_MANAGEMENT;